### ISSUE TITLE
Remove (not hide) axis for small chart with a lot of data

### ISSUE THREAD

**Issue by Maxwell2022** [chinmaymk/angular-charts#62]
For very small chart having the axis graduation makes it useless because impossible to read. Is it possible to hide the axis?

![screen shot 2014-05-19 at 3 05 56 pm](https://cloud.githubusercontent.com/assets/670701/3010459/5d8a8c36-df13-11e3-998b-5fe8e4571ed2.png)

At the moment I'm doing it in CSS with the following code:

``` css
#chart .y.axis .tick,
#chart .x.axis .tick {
    display: none !important;
}
```

But it's just hiding the ticks and there is now a blank section where the axis tick label should be.
![screen shot 2014-05-19 at 3 04 09 pm](https://cloud.githubusercontent.com/assets/670701/3010448/2d8d3de4-df13-11e3-9f6f-6f68f94586db.png)
